# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import leader_election_pb2 as leader__election__pb2


class ElectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Elect = channel.unary_unary(
                '/Election/Elect',
                request_serializer=leader__election__pb2.ElectionRequest.SerializeToString,
                response_deserializer=leader__election__pb2.ElectionResponse.FromString,
                )
        self.AnnounceLeader = channel.unary_unary(
                '/Election/AnnounceLeader',
                request_serializer=leader__election__pb2.LeaderRequest.SerializeToString,
                response_deserializer=leader__election__pb2.LeaderResponse.FromString,
                )


class ElectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Elect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnnounceLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Elect': grpc.unary_unary_rpc_method_handler(
                    servicer.Elect,
                    request_deserializer=leader__election__pb2.ElectionRequest.FromString,
                    response_serializer=leader__election__pb2.ElectionResponse.SerializeToString,
            ),
            'AnnounceLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.AnnounceLeader,
                    request_deserializer=leader__election__pb2.LeaderRequest.FromString,
                    response_serializer=leader__election__pb2.LeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Election', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Election(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Elect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Election/Elect',
            leader__election__pb2.ElectionRequest.SerializeToString,
            leader__election__pb2.ElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnnounceLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Election/AnnounceLeader',
            leader__election__pb2.LeaderRequest.SerializeToString,
            leader__election__pb2.LeaderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
