# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lamport_pb2 as lamport__pb2


class LamportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResolveEvent = channel.unary_unary(
                '/lamport.LamportService/ResolveEvent',
                request_serializer=lamport__pb2.EventRequest.SerializeToString,
                response_deserializer=lamport__pb2.EventResponse.FromString,
                )


class LamportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResolveEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LamportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResolveEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEvent,
                    request_deserializer=lamport__pb2.EventRequest.FromString,
                    response_serializer=lamport__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lamport.LamportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LamportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResolveEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/lamport.LamportService/ResolveEvent',
            lamport__pb2.EventRequest.SerializeToString,
            lamport__pb2.EventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
