# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: leader_election.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15leader_election.proto\"\"\n\x0f\x45lectionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\"\n\rLeaderRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"\x1c\n\x0eLeaderResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32k\n\x08\x45lection\x12,\n\x05\x45lect\x12\x10.ElectionRequest\x1a\x11.ElectionResponse\x12\x31\n\x0e\x41nnounceLeader\x12\x0e.LeaderRequest\x1a\x0f.LeaderResponseb\x06proto3')



_ELECTIONREQUEST = DESCRIPTOR.message_types_by_name['ElectionRequest']
_ELECTIONRESPONSE = DESCRIPTOR.message_types_by_name['ElectionResponse']
_LEADERREQUEST = DESCRIPTOR.message_types_by_name['LeaderRequest']
_LEADERRESPONSE = DESCRIPTOR.message_types_by_name['LeaderResponse']
ElectionRequest = _reflection.GeneratedProtocolMessageType('ElectionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONREQUEST,
  '__module__' : 'leader_election_pb2'
  # @@protoc_insertion_point(class_scope:ElectionRequest)
  })
_sym_db.RegisterMessage(ElectionRequest)

ElectionResponse = _reflection.GeneratedProtocolMessageType('ElectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ELECTIONRESPONSE,
  '__module__' : 'leader_election_pb2'
  # @@protoc_insertion_point(class_scope:ElectionResponse)
  })
_sym_db.RegisterMessage(ElectionResponse)

LeaderRequest = _reflection.GeneratedProtocolMessageType('LeaderRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEADERREQUEST,
  '__module__' : 'leader_election_pb2'
  # @@protoc_insertion_point(class_scope:LeaderRequest)
  })
_sym_db.RegisterMessage(LeaderRequest)

LeaderResponse = _reflection.GeneratedProtocolMessageType('LeaderResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEADERRESPONSE,
  '__module__' : 'leader_election_pb2'
  # @@protoc_insertion_point(class_scope:LeaderResponse)
  })
_sym_db.RegisterMessage(LeaderResponse)

_ELECTION = DESCRIPTOR.services_by_name['Election']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELECTIONREQUEST._serialized_start=25
  _ELECTIONREQUEST._serialized_end=59
  _ELECTIONRESPONSE._serialized_start=61
  _ELECTIONRESPONSE._serialized_end=91
  _LEADERREQUEST._serialized_start=93
  _LEADERREQUEST._serialized_end=127
  _LEADERRESPONSE._serialized_start=129
  _LEADERRESPONSE._serialized_end=157
  _ELECTION._serialized_start=159
  _ELECTION._serialized_end=266
# @@protoc_insertion_point(module_scope)
